from decimal import *
from datetime import *
from typing import *

from dataclasses import dataclass
from marshmallow import Schema, fields, post_load
from openfabric_pysdk.utility import SchemaUtil


################################################################
# Input concept class - AUTOGENERATED
################################################################
@dataclass
class InputClass:
    prompt: str = None
    ai_enhaned: bool = False
    session_id: str = None   
    recallLongTermMemory: bool = False
    # attachments: List[str] = None



################################################################
# InputSchema concept class - AUTOGENERATED
################################################################
class InputClassSchema(Schema):
    prompt = fields.String(allow_none=True)
    # attachments = fields.List(fields.String(allow_none=True), allow_none=True)
    ai_enhaned = fields.Boolean(allow_none=True, default=False)
    session_id = fields.String(allow_none=True)
    recallLongTermMemory = fields.Boolean(allow_none=True, default=False)

    @post_load
    def create(self, data, **kwargs):
        return SchemaUtil.create(InputClass(), data)
